### ISSUE TITLE
Feat request: add mathematic operators search options.

### ISSUE THREAD

**Issue by FrankyCTY** [thangpham7793/headwind_lookup#3]
Something like **hw margin gt 20** and should list out all the margin with value greater than 20.

**Comment by thangpham7793** [comment]
Potential issue is that the `search` currently matches any utility class, css prop or css value, so we need it not to be fuzzy.

Maybe we will only accept a valid number utility class (mt, mx, my, etc.) to use this feature.

```bash
hw mt gte 20
```

Thoughts?

**Comment by thangpham7793** [comment]
Another possible solution is to treat this as a 2 step process. So `hw margin gt 20` will search for anything that has `margin`, and then keep only the utility classes with a number value > 20.

**Comment by thangpham7793** [comment]
Implemented
